[2024-01-06T06:21:01.586+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-01-06T06:20:57.187768+00:00 [queued]>
[2024-01-06T06:21:01.596+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-01-06T06:20:57.187768+00:00 [queued]>
[2024-01-06T06:21:01.597+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-01-06T06:21:01.614+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-01-06 06:20:57.187768+00:00
[2024-01-06T06:21:01.620+0000] {standard_task_runner.py:57} INFO - Started process 442 to run task
[2024-01-06T06:21:01.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2024-01-06T06:20:57.187768+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpk8d_tr6q']
[2024-01-06T06:21:01.656+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask python_job
[2024-01-06T06:21:01.778+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2024-01-06T06:20:57.187768+00:00 [running]> on host 2e2e3a50c188
[2024-01-06T06:21:01.907+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T06:20:57.187768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-06T06:20:57.187768+00:00'
[2024-01-06T06:21:01.920+0000] {spark_submit.py:236} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-01-06T06:21:01.920+0000] {spark_submit.py:366} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2024-01-06T06:21:02.107+0000] {spark_submit.py:536} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-06T06:21:04.118+0000] {spark_submit.py:536} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-01-06T06:21:04.119+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-01-06T06:21:04.119+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-01-06T06:21:04.119+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-01-06T06:21:04.119+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-01-06T06:21:04.120+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-01-06T06:21:04.120+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-01-06T06:21:04.120+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-01-06T06:21:04.120+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-01-06T06:21:04.120+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-01-06T06:21:04.121+0000] {spark_submit.py:536} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-01-06T06:21:04.141+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 467, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2024-01-06T06:21:04.146+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20240106T062057, start_date=20240106T062101, end_date=20240106T062104
[2024-01-06T06:21:04.156+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 442)
[2024-01-06T06:21:04.171+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-06T06:21:04.195+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
